export const metadata = {
  title: "Contact Us || My Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>Welcome to Contact Us Page!{children}</body>
    </html>
  );
}
