import { Inter } from "next/font/google";
import MyContext from "@/Helper/Context";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "My Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={inter.className}>
        <MyContext>{children}</MyContext>
      </body>
    </html>
  );
}
